export const ELIGIBILITY_KEYS = Object.freeze({
  DATE_OF_BIRTH_REQUIRED: 'eligibility.dateOfBirthRequired',
  MINIMUM_AGE: 'eligibility.minimumAge',
  INVALID_DATE_OF_BIRTH: 'eligibility.invalidDateOfBirth',
  AGE_VERIFICATION_FAILED: 'eligibility.ageVerificationFailed',
  DONOR_NOT_FOUND: 'eligibility.donorNotFound',
  DONOR_OR_REQUEST_NOT_FOUND: 'eligibility.donorOrRequestNotFound',
  DONOR_OPTED_OUT_OF_MATCHING: 'eligibility.donorOptedOutOfMatching',
  DONOR_HAS_NO_BLOOD_TYPE: 'eligibility.donorHasNoBloodType',
  BLOOD_TYPE_INCOMPATIBLE: 'eligibility.bloodTypeIncompatible',
  MATCHING_LOCATION_UNAVAILABLE: 'eligibility.matchingLocationUnavailable',
  OUTSIDE_MATCHING_RADIUS: 'eligibility.outsideMatchingRadius',
  REQUEST_NOT_FOUND: 'eligibility.requestNotFound',
  DONOR_ELIGIBLE: 'eligibility.donorEligible',
  DONOR_NOT_ELIGIBLE: 'eligibility.donorNotEligible',
  NO_TEMPORARY_DEFERRAL: 'eligibility.noTemporaryDeferral',
  TEMPORARY_DEFERRAL_EXPIRED: 'eligibility.temporaryDeferralExpired',
  TEMPORARILY_DEFERRED: 'eligibility.temporarilyDeferred',
  TRAVEL_DEFERRAL: 'eligibility.travelDeferral',
  NO_DONATION_INTERVAL_RESTRICTION: 'eligibility.noDonationIntervalRestriction',
  INVALID_LAST_DONATION_DATE_IGNORED: 'eligibility.invalidLastDonationDateIgnored',
  DONATION_COOLDOWN_ACTIVE: 'eligibility.donationCooldownActive',
  DONATION_INTERVAL_SATISFIED: 'eligibility.donationIntervalSatisfied',
  NO_HEMOGLOBIN_RESTRICTION: 'eligibility.noHemoglobinRestriction',
  HEMOGLOBIN_BELOW_MINIMUM: 'eligibility.hemoglobinBelowMinimum',
  HEMOGLOBIN_LEVEL_ACCEPTABLE: 'eligibility.hemoglobinLevelAcceptable',
  DONOR_SUSPENDED: 'eligibility.donorSuspended',
  DONOR_CURRENTLY_UNAVAILABLE: 'eligibility.donorCurrentlyUnavailable',
  REQUEST_NO_LONGER_ACTIVE: 'eligibility.requestNoLongerActive',
});

export default ELIGIBILITY_KEYS;